### ISSUE TITLE
📚 Documentation: Write inline documentation for communications/message.py

### ISSUE THREAD

**Issue by ramesht007** [NimbleEdge/EnvisEdge#137]
###  🙋 Where

File [Link](https://github.com/NimbleEdge/RecoEdge/blob/main/fedrec/communications/messages.py)
https://github.com/NimbleEdge/RecoEdge/blob/7d9253c5a05a567a4151ecfd67794ab0565d5aff/fedrec/communications/messages.py#L10
https://github.com/NimbleEdge/RecoEdge/blob/7d9253c5a05a567a4151ecfd67794ab0565d5aff/fedrec/communications/messages.py#L26
https://github.com/NimbleEdge/RecoEdge/blob/7d9253c5a05a567a4151ecfd67794ab0565d5aff/fedrec/communications/messages.py#L51

### 💭 Description

We need to go "line-by-line" and create inline documentation for this file. Please try to use proper punctuation and English grammar to the best of your ability.

We are using the pep8 format for documentation. The following links are concise and would be very useful:
- pep8 [guidelines](https://www.python.org/dev/peps/pep-0008/)
- numpy style [guide](https://numpydoc.readthedocs.io/en/latest/format.html)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the guidlines?

- [X] I have read the Guildlines

### 🏢 Have you read the Code of Conduct?

- [X] I read the Code of Conduct

**Comment by eshaanagarwal** [comment]
hi @ramesht007 ! Can this issue be assigned to me? My PR is almost ready.
