### ISSUE TITLE
📚 Documentation: Write Inline documentation for utilities/serialization.py

### ISSUE THREAD

**Issue by divyanshugit** [NimbleEdge/EnvisEdge#163]
###  🙋 Where

File: [link](https://github.com/NimbleEdge/EnvisEdge/blob/main/fedrec/utilities/serialization.py)

### 💭 Description

We need to go "line-by-line" and create inline documentation for this file. Please try to use proper punctuation and English grammar to the best of your ability.

We are using the pep8 format for documentation. The following links are concise and would be very useful:
- pep8 [guidelines](https://www.python.org/dev/peps/pep-0008/)
- NumPy style [guide](https://numpydoc.readthedocs.io/en/latest/format.html)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the guidlines?

- [X] I have read the Guildlines

### 🏢 Have you read the Code of Conduct?

- [X] I read the Code of Conduct

**Comment by Jenniline** [comment]
Hi @divyanshugit and @vkkhare  I am interested in working on this issue.

**Comment by vkkhare** [comment]
Sure @Jenniline please go ahead!

**Comment by adinayyu** [comment]
@vkkhare @divyanshugit I am adithya from India and to apply for gsod 2022 I have created a pull request for this issue. This is my first pull request for nimbleedge. Check the pr and inform me what to do if something is wrong.
#180

**Comment by ramesht007** [comment]
This file has been removed
