### ISSUE TITLE
📚 Documentation: 

### ISSUE THREAD

**Issue by kaiserliche** [NimbleEdge/EnvisEdge#169]
###  🙋 Where

On the EvisEdge's Readme page, precisely under QuickStart.

### 💭 Description

Create an introductory tutorial on Google Colab Notebook for EnvisEdge.
Refer to the following repo(open in colab): https://github.com/ploomber/ploomber

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the guidlines?

- [X] I have read the Guildlines

### 🏢 Have you read the Code of Conduct?

- [X] I read the Code of Conduct

**Comment by abhiwalia15** [comment]
Is this issue open? I would like to work on this.

Let me know, thanks.

**Comment by ramesht007** [comment]
Hey @abhiwalia15 ,
This is issue is open but there are still blockers that need to be resolved before this can be done.
Thanks for taking interest, please feel free to take up another issue.
thanks

**Comment by abhiwalia15** [comment]
> Hey @abhiwalia15 , This is issue is open but there are still blockers that need to be resolved before this can be done. Thanks for taking interest, please feel free to take up another issue. thanks

Thanks for letting me know. I will look for another issue of my interest.

**Comment by ramesht007** [comment]
Completed in #184
