### ISSUE TITLE
📚 Documentation: Write Inline documentation for job_response_model.py

### ISSUE THREAD

**Issue by ramesht007** [NimbleEdge/EnvisEdge#186]
###  🙋 Where

Here:
- https://github.com/NimbleEdge/EnvisEdge/blob/00f554973085c54da98caf37721bec27ba07380d/fedrec/data_models/job_response_model.py#L53
- https://github.com/NimbleEdge/EnvisEdge/blob/00f554973085c54da98caf37721bec27ba07380d/fedrec/data_models/job_response_model.py#L64

### 💭 Description

We need to go "line-by-line" and create inline documentation for this file. Please try to use proper punctuation and English grammar to the best of your ability.

We are using the pep8 format for documentation. The following links are concise and would be very useful:

pep8 [guidelines](https://www.python.org/dev/peps/pep-0008/)
numpy style [guide](https://numpydoc.readthedocs.io/en/latest/format.html)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the guidlines?

- [X] I have read the Guildlines

### 🏢 Have you read the Code of Conduct?

- [X] I read the Code of Conduct

**Comment by Tob-iee** [comment]
I would like to handle this issue, please assign this to me
