### ISSUE TITLE
📚 Documentation: Broken link in Starting with NimbleEdge

### ISSUE THREAD

**Issue by haripriya9647** [NimbleEdge/EnvisEdge#207]
###  🙋 Where

https://docs.nimbleedge.ai/tutorials/tutorial-part-2-starting_with_nimbleedge

### 💭 Description

Line no - 51
Please discuss with maintainer regarding the broken link before submitting a pr

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the guidlines?

- [X] I have read the Guildlines

### 🏢 Have you read the Code of Conduct?

- [X] I read the Code of Conduct

**Comment by divyanshugit** [comment]
We already have this issue #170

**Comment by haripriya9647** [comment]
Oops I am closing this
