### ISSUE TITLE
📚 Documentation: Fixing grammar in GitHub Readme of EnvisEdge

### ISSUE THREAD

**Issue by burpcat** [NimbleEdge/EnvisEdge#209]
###  🙋 Where

Issue needs to be fixed at "https://github.com/NimbleEdge/EnvisEdge" in the Repo Structure

### 💭 Description

Correct kafka spelling in Repo Structure part of the readme

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the guidlines?

- [X] I have read the Guildlines

### 🏢 Have you read the Code of Conduct?

- [x] I read the Code of Conduct

**Comment by burpcat** [comment]
@ramesht007. Since this is a minuscule issue. I went ahead and fixed the issue and created a PR. Hope its okay

**Comment by ramesht007** [comment]
Hey @burpcat ,
Thanks for pointing out the mistake.
Please take up another open issue and fix this mistake with that.
thanks for understanding.
