### ISSUE TITLE
📚 Documentation: Fixing a broken link in the TUTORIALS section

### ISSUE THREAD

**Issue by Gaurav4code** [NimbleEdge/EnvisEdge#211]
###  🙋 Where

https://github.com/NimbleEdge/EnvisEdge/blob/main/docs/source/tutorials/Tutorial-Part-6-customization.rst

### 💭 Description

 `Broken Links` :
-    **Customization**
-      Training Configuration
          Line  - 14
-      Model Architecture
           Line - 56
                                 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the guidlines?

- [X] I have read the Guildlines

### 🏢 Have you read the Code of Conduct?

- [X] I read the Code of Conduct

**Comment by divyanshugit** [comment]
@Gaurav4code we already have an issue for this as #170

**Comment by divyanshugit** [comment]
@Gaurav4code Can you please go through the open issues before creating an issue!!

**Comment by Gaurav4code** [comment]
Ok ,sure should I just close this issue

**Comment by divyanshugit** [comment]
Yupp, that will be great.
