### ISSUE TITLE
📚 Documentation: Updating the repo structure

### ISSUE THREAD

**Issue by soma2000-lang** [NimbleEdge/EnvisEdge#216]
###  🙋 Where

[here](https://github.com/NimbleEdge/EnvisEdge/blob/main/README.md)

### 💭 Description

There have been a few typos in the repo structure of the readme.md file. I have fixed that.

### 👀 Have you spent some time checking if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the guidlines?

- [X] I have read the Guildlines

### 🏢 Have you read the Code of Conduct?

- [X] I read the Code of Conduct

**Comment by ramesht007** [comment]
This issue has already been put up, 
Please first check and then create the issue, so that it is easy to track.
thanks
