### ISSUE TITLE
📚 Documentation: Fix broken links in tutorial section

### ISSUE THREAD

**Issue by Mr-Destructive** [NimbleEdge/EnvisEdge#217]
###  🙋 Where

PATH: https://github.com/NimbleEdge/EnvisEdge/blob/main/docs/source/tutorials/Tutorial-Part-6-customization.rst

### 💭 Description

A couple of links in the following sections are broken :
- Training Configuration (for training config flags)
- Model Architecture --> Adding new models (for fedrec modules)

There is already a closed issue on this #211 but it was redirected to #170

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the guidlines?

- [X] I have read the Guildlines

### 🏢 Have you read the Code of Conduct?

- [X] I read the Code of Conduct

**Comment by nelsonmic** [comment]
Hi there, I would like this task to be assigned to me

**Comment by ramesht007** [comment]
HI, @nelsonmic
Please comment on issue #205 where volunteers are working to fix all the tutorials. You can also help them out.
thanks
