### ISSUE TITLE
📚 Documentation: improve tutorials 

### ISSUE THREAD

**Issue by ramesht007** [NimbleEdge/EnvisEdge#237]
###  🙋 Where

[Here](https://github.com/NimbleEdge/EnvisEdge/tree/main/docs/source/tutorials)

### 💭 Description

We need to improve the tutorials for android and iOS for federated learning.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the guidlines?

- [X] I have read the Guildlines

### 🏢 Have you read the Code of Conduct?

- [X] I read the Code of Conduct

**Comment by divyanshugit** [comment]
Hi @ramesht007, I would love to work on this.

**Comment by Tob-iee** [comment]
@ramesht007 @divyanshugit

**Comment by Dule-mart** [comment]
@ramesht007 @divyanshugit @Tob-iee  great doing this with you guy ❤️

**Comment by MasterBlaster99** [comment]
@ramesht007 @divyanshugit

**Comment by haripriya9647** [comment]
@ramesht007 @divyanshugit

**Comment by ramesht007** [comment]
Thanks for helping us everyone!!.
Happy Open-Sourcing ❤️
