### ISSUE TITLE
Document Preprocessor Class

### ISSUE THREAD

**Issue by vkkhare** [NimbleEdge/EnvisEdge#25]
[This class](https://github.com/NimbleEdge/RecoEdge/blob/main/fedrec/preprocessor.py) sets the dataset for each of the workers.

**Comment by Bennykillua** [comment]
I will like to try issue 25

**Comment by vkkhare** [comment]
Sure thanks for joining in the effort. We have assigned you the issue

**Comment by imanishbarnwal** [comment]
Hey if no one is working on this issue can I take it? I want to work on this issue thank you!!

**Comment by ramesht007** [comment]
This module has been removed.

**Comment by ramesht007** [comment]
This module has been removed.
