### ISSUE TITLE
📚 Documentation: Write inline documentation for fedrec/multiprocessing/jobber.py

### ISSUE THREAD

**Issue by ramesht007** [NimbleEdge/EnvisEdge#51]
# Where?

HERE-
- https://github.com/NimbleEdge/EnvisEdge/blob/00f554973085c54da98caf37721bec27ba07380d/fedrec/multiprocessing/jobber.py#L62
- https://github.com/NimbleEdge/EnvisEdge/blob/00f554973085c54da98caf37721bec27ba07380d/fedrec/multiprocessing/jobber.py#L79
- https://github.com/NimbleEdge/EnvisEdge/blob/00f554973085c54da98caf37721bec27ba07380d/fedrec/multiprocessing/jobber.py#L86

# Who?

Anyone who wants to get know the code base of NimbleEdge as well as any file in the project.

# What?

Please follow these guidelines: [LInk](https://numpydoc.readthedocs.io/en/latest/format.html)
We need to go "line-by-line" and create inline documentation for this file. Please try to use proper punctuation and English grammar to the best of your ability.

# Additional Content

We need to go "line-by-line" and create inline documentation for this file. Please try to use proper punctuation and English grammar to the best of your ability.

We are using the pep8 format for documentation. The following links are concise and would be very useful:

pep8 [guidelines](https://www.python.org/dev/peps/pep-0008/)
numpy style [guide](https://numpydoc.readthedocs.io/en/latest/format.html)

**Comment by vivekagarwal2349** [comment]
hi @ramesht007 , i would like to work on this.

**Comment by abhiwalia15** [comment]
Hello @ramesht007, let me know if this issue is available and if yes, please assign it to me.

Thanks

**Comment by ramesht007** [comment]
Hey @abhiwalia15 ,
this issue is still not done.
please take this up
thanks

**Comment by abhiwalia15** [comment]
> Hey @abhiwalia15 , this issue is still not done. please take this up thanks

I am on it. Thanks
