### ISSUE TITLE
📚 Documentation: Write inline documentation for fedrec/python_executors/aggregator.py

### ISSUE THREAD

**Issue by ramesht007** [NimbleEdge/EnvisEdge#62]
# Where?

[Here](https://github.com/NimbleEdge/RecoEdge/blob/main/fedrec/python_executors/aggregator.py)

# Who?

Anyone who wants to get know the code base of NimbleEdge as well as any file in the project.

# What?

Please follow these guidelines: [Link](https://numpydoc.readthedocs.io/en/latest/format.html)
We need to go "line-by-line" and create inline documentation for this file. Please try to use proper punctuation and English grammar to the best of your ability.

# Additional Content 

None

**Comment by Tob-iee** [comment]
Has this tack been assigned to anyone, If not I would like to take it up

**Comment by ramesht007** [comment]
hey @Tob-iee ,
thanks for taking interest.
Assigned you the issue.

**Comment by ramesht007** [comment]
This issue has been completed.
