### ISSUE TITLE
📚 Documentation: Create Documentation pages

### ISSUE THREAD

**Issue by ramesht007** [NimbleEdge/EnvisEdge#68]
In [docs](https://github.com/NimbleEdge/RecoEdge/tree/main/docs) folder we have to create two folders tutorials and API docs folder.

**Comment by divyanshugit** [comment]
I would like to take it.

**Comment by ramesht007** [comment]
Thanks for showing interest. @divyanshugit 
Assigned you.

**Comment by ramesht007** [comment]
TODO tasks:

- [ ] Add repo structure to documentation
- [ ] Add hyper link to repo folder for user navigation
- [ ] Adds tabs to page
- [ ] Refactor discord shield
- [ ] remove small recoedge
- [ ] fix pages that have no documentation

**Comment by Dule-mart** [comment]
I can see that after the work done by @divyanshugit this issue is still open, would love to work on it but will need a little guide on where and what to start with.

**Comment by Dule-mart** [comment]
Thanks!

**Comment by ramesht007** [comment]
@Dule-mart feel free to take up another issue!!
